# ######################################################################################
# Copyright 2021 by tobi@backfrak.de. All
# rights reserved. Use of this source code is governed
# by a BSD-style license that can be found in the
# LICENSE file.
# ######################################################################################
# Container image used by the github workflow to run integration tests
# ######################################################################################

# Use the same ubuntu version as for main development for this test
FROM debian:bullseye

# Install needed packages
RUN apt-get update && apt-get install -y wget curl coreutils mawk procps

# Copy test scripts
COPY test/integrationTest/scripts/RunIntegrationTests.sh /RunIntegrationTests.sh
RUN chmod 777 /RunIntegrationTests.sh
COPY test/import/functions.sh /functions.sh
RUN chmod 777 /functions.sh

# The bin/samba_exporter from build output is restored as bin/samba_exporter/samba_exporter
COPY bin/samba_exporter /samba_exporter
RUN chmod 777 /samba_exporter/samba_exporter

# The bin/samba_statusd from build output is restored as bin/samba_statusd/samba_statusd 
COPY bin/samba_statusd  /samba_statusd
RUN chmod 777 /samba_statusd/samba_statusd 
