# Container image that runs your code
FROM ubuntu:groovy

# Copies your code file from your action repository to the filesystem path `/` of the container
COPY ../scripts/RunIntegrationTests.sh /RunIntegrationTests.sh
COPY ../../bin/samba_exporter /samba_exporter
COPY ../../bin/samba_statusd  /samba_statusd

# Code file to execute when the docker container starts up (`RunIntegrationTests.sh`)
ENTRYPOINT ["/RunIntegrationTests.sh"]