{
 "title": "Samba Service V0.5",
 "description": "Dashboard for the Samba Server at ${SAMBA_SERVER}",
 "tags": [ "Service" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Samba Clients",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "samba_client_count{instance=\"${SAMBA_SERVER}:9922\"}",
     "legendFormat": "Client Count"
    }
   ]
  },
  {
   "title": "Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "samba_individual_user_count{instance=\"${SAMBA_SERVER}:9922\"}",
     "legendFormat": "Samba Users "
    }
   ]
  },
  {
   "title": "Locks per share",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "samba_locks_per_share_count{instance=\"${SAMBA_SERVER}:9922\"}",
     "legendFormat": "Loks on  {{share}}"
    }
   ]
  },
  {
   "title": "Share Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "samba_share_count{instance=\"${SAMBA_SERVER}:9922\"}",
     "legendFormat": "Used Shares"
    }
   ]
  },
  {
   "title": "Protocol Details",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "samba_signing_method_count{instance=\"${SAMBA_SERVER}:9922\"}",
     "legendFormat": "Signing: {{signing}}"
    },
    {
     "expr": "samba_encryption_method_count{instance=\"${SAMBA_SERVER}:9922\"}",
     "legendFormat": "Encryption: {{encryption}}"
    },
    {
     "expr": "samba_protocol_version_count{instance=\"${SAMBA_SERVER}:9922\"}",
     "legendFormat": "Version: {{protocol_version}}"
    }
   ]
  },
  {
   "title": "Request duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": "samba_request_time{instance=\"${SAMBA_SERVER}:9922\"}",
     "legendFormat": "Request Time"
    }
   ]
  }
 ]
}