#!/bin/sh

set -e

case "$1" in
  purge)
        # In case the pacakge gets purged, we remove the daemon user
        deluser --system samba-exporter
        delgroup --system samba-exporter
        systemctl daemon-reload
    ;;
  remove)
        # When the package got removed the service files got deleted. So systemd can now remove the services from its internal db
        systemctl daemon-reload
    ;;
esac